#!/bin/bash

# ask user for version bump type
read -rp "What type of version bump? (major/minor/patch): " bumpType

# if user provides a valid version bump type, bump the version
if [ "$bumpType" = "major" ] || [ "$bumpType" = "minor" ] || [ "$bumpType" = "patch" ]; then
  bunx np --no-tests --no-publish --no-cleanup "$bumpType"
else
  echo "Invalid version bump type. Exiting..."
fi